name: Terraform CI/CD (Plan + Apply After Merge)

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  TF_VERSION: 1.6.6
  TF_WORKING_DIR: prod-infra

jobs:
  terraform-plan:
    name: Terraform Plan (PR)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan.out

      - name: Save Plan Output (for visibility)
        run: terraform show -no-color tfplan.out > plan-output.txt

      - name: Upload Plan Files
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            ${{ env.TF_WORKING_DIR }}/tfplan.out
            ${{ env.TF_WORKING_DIR }}/plan-output.txt

      - name: Show Plan in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/plan-output.txt

  terraform-apply:
    name: Terraform Apply (After Merge)
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Download Plan Artifact (Optional)
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Before Apply)
        id: plan-verify
        run: terraform plan -out=tfplan-apply.out

      - name: Show Apply Plan Output
        run: terraform show -no-color tfplan-apply.out

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan-apply.out

      - name: Deployment Success Notification
        if: success()
        run: |
          echo "✅ Terraform apply completed successfully!"
          echo "🚀 Infrastructure has been deployed to AWS!"
