name: Terraform Deploy

on:
  # Trigger when code is merged (PR closed & merged) into main branch
  pull_request:
    branches:
      - main
    types:
      - closed

  # Trigger manually as well
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_REGION: ap-south-1
  TF_WORKING_DIR: prod-infra

jobs:
  terraform:
    name: Terraform Init, Validate, Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Upload Plan File
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

  manual_approval:
    name: Manual Approval (Click Play to Continue)
    needs: terraform
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && github.base_ref == 'main') }}

    steps:
      - name: Await Manual Approval
        run: |
          echo "✅ Terraform Plan completed successfully."
          echo "📝 Please review the plan artifact before applying."
          echo "▶️ Click the 'Run job' (play button) in this step to continue to Apply."

  apply:
    name: Terraform Apply (Manual Trigger)
    needs: manual_approval
    runs-on: ubuntu-latest
    environment:
      name: production   # 👈 Add manual reviewers under Repo → Settings → Environments → production

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Download Plan File
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Deployment Success Notification
        if: success()
        run: |
          echo "✅ Terraform apply completed successfully!"
          echo "🚀 Infrastructure deployed to AWS."